### ISSUE TITLE
PF 制下绩点似乎会被记作 4 而非不计入绩点

### ISSUE THREAD

**Issue by Xzonn** [pkuhelper-web/score#2]
如题，本学期部分体育课采取 P/F 制，从信息门户来看“P”绩点等于 4，被计入绩点计算，而网页版似乎没有计入绩点计算。
![批注 2020-06-08 161728](https://user-images.githubusercontent.com/30619816/84007946-afa7e200-a9a3-11ea-9f7d-2c390e3f5dde.png)
![批注 2020-06-08 161739](https://user-images.githubusercontent.com/30619816/84007947-b0407880-a9a3-11ea-97d7-9bedaedb6f20.png)
![批注 2020-06-08 161804](https://user-images.githubusercontent.com/30619816/84008114-f7c70480-a9a3-11ea-9049-542fbdf7601b.png)

**Comment by xmcp** [comment]
好像又有人说体育不算绩点了……搞不懂
